//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiRehber
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UyelerEntities4 : DbContext
    {
        public UyelerEntities4()
            : base("name=UyelerEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KullaniciBilgileri> KullaniciBilgileri { get; set; }
        public virtual DbSet<RehberBilgileri> RehberBilgileri { get; set; }
    }
}
