//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisiRehber
{
    using System;
    using System.Collections.Generic;
    
    public partial class RehberBilgileri
    {
        public int id { get; set; }
        public string İsim { get; set; }
        public string TelefonNo { get; set; }
    }
}
